# Generated by Django 5.1.6 on 2025-02-14 08:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_remove_chatmessage_message_remove_chatmessage_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(default='Message'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender',
            field=models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], default='bot', max_length=10),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
