# Generated by Django 5.1.6 on 2025-02-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_chatmessage_message_chatmessage_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='chat_id',
            field=models.TextField(default='bot'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.TextField(choices=[('user', 'User'), ('bot', 'Bot')], default='bot'),
        ),
    ]
